tabs:
  content:
    label: Inhalte & Seiten
    columns:
      left:
        width: 2/3
        fields:
          content: fields/groups/group-content
      right:
        width: 1/3
        sections:
          published: sections/pages-published
          drafts: sections/pages-drafts

  files:
    label: Dateien
    sections:
      files: sections/files-files

  meta:
    label: Meta
    fields:
      meta: fields/groups/group-meta

  info:
    label: Info
    sections:
      info: sections/stats-info
